#ifndef __HI_MOTOR_H__ 
#define __HI_MOTOR_H__

typedef enum
{
	MOTOR_DIRECT_UP,
	MOTOR_DIRECT_DOWN,
	MOTOR_DIRECT_LEFT,
	MOTOR_DIRECT_RIGHT,
	MOTOR_DIRECT_STOP,
	MOTOR_DIRECT_LEFTUP,
	MOTOR_DIRECT_RIGHTUP,
	MOTOR_DIRECT_LEFTDOWN,
	MOTOR_DIRECT_RIGHTDOWN,
}MotorDirect_e;

#define MOTOR_SET_START		1
#define MOTOR_SET_DIRECT	3
#define MOTOR_SET_DELAY		4
#define MOTOR_SET_STOP		5
#define MOTOR_SET_UD_STEP	6
#define MOTOR_SET_LR_STEP	7
#define MOTOR_SET_UD_WORK	8
#define MOTOR_SET_LR_WORK	9
#define MOTOR_GET_DONE		10
#define MOTOR_GET_UD_STEP	11
#define MOTOR_GET_LR_STEP	12
#define MOTOR_TEST			255

char BJSensorDetect(char dir);

#endif
